<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'FGW' => 1,
        'XTYJRJ' => 2,
        'XGXJ' => 3,
        'XGAJ' => 4,
        'XCZJ' => 5,
        'XWJJ' => 6,
        'XSJJ' => 7,
        'XZJJ' => 8,
        'XRSJ' => 9,
        'XJTJ' => 10,
        'XSLJ' => 11,
        'XNYNCJ' => 12,
        'XSTJ' => 13,
        'XSFJ' => 14,
        'XLYJ' => 15,
        'XZRZYJ' => 16,
        'XTJJ' => 17,
        'XXZSPJ' => 18,
        'XSCJGJ' => 19,
        'XYBJ' => 20,
        'XYJJ' => 21,
        'XNYJ' => 22,
        'XWLJ' => 23,
        'XXFJ' => 24,
        'XFPB' => 25,
        'XMZJ' => 26,
        'WFZ' => 27,
        'CJYX' => 28,
        'WTZ' => 29,
        'WJTZ' => 30,
        'AJWX' => 31,
        'KNZ' => 32,
        'CJHZ' => 33,
        'LYKZ' => 34,
        'GJCZ' => 35,
        'DHX' => 36,
        'MJPX' => 37,
        'GXX' => 38,
        'JLSX' => 39,
        'ZJPX' => 40,
        'GDSX' => 41,
        'SWJ' => 42,
        'RMFY' => 43,
    );
}
