<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['FGW'] => 'FGW',
        IUserGroup::ID['XTYJRJ'] => 'XTYJRJ',
        IUserGroup::ID['XGXJ'] => 'XGXJ',
        IUserGroup::ID['XGAJ'] => 'XGAJ',
        IUserGroup::ID['XCZJ'] => 'XCZJ',
        IUserGroup::ID['XWJJ'] => 'XWJJ',
        IUserGroup::ID['XSJJ'] => 'XSJJ',
        IUserGroup::ID['XZJJ'] => 'XZJJ',
        IUserGroup::ID['XRSJ'] => 'XRSJ',
        IUserGroup::ID['XJTJ'] => 'XJTJ',
        IUserGroup::ID['XSLJ'] => 'XSLJ',
        IUserGroup::ID['XNYNCJ'] => 'XNYNCJ',
        IUserGroup::ID['XSTJ'] => 'XSTJ',
        IUserGroup::ID['XSFJ'] => 'XSFJ',
        IUserGroup::ID['XLYJ'] => 'XLYJ',
        IUserGroup::ID['XZRZYJ'] => 'XZRZYJ',
        IUserGroup::ID['XTJJ'] => 'XTJJ',
        IUserGroup::ID['XXZSPJ'] => 'XXZSPJ',
        IUserGroup::ID['XSCJGJ'] => 'XSCJGJ',
        IUserGroup::ID['XYBJ'] => 'XYBJ',
        IUserGroup::ID['XYJJ'] => 'XYJJ',
        IUserGroup::ID['XNYJ'] => 'XNYJ',
        IUserGroup::ID['XWLJ'] => 'XWLJ',
        IUserGroup::ID['XXFJ'] => 'XXFJ',
        IUserGroup::ID['XFPB'] => 'XFPB',
        IUserGroup::ID['XMZJ'] => 'XMZJ',
        IUserGroup::ID['WFZ'] => 'WFZ',
        IUserGroup::ID['CJYX'] => 'CJYX',
        IUserGroup::ID['WTZ'] => 'WTZ',
        IUserGroup::ID['WJTZ'] => 'WJTZ',
        IUserGroup::ID['AJWX'] => 'AJWX',
        IUserGroup::ID['KNZ'] => 'KNZ',
        IUserGroup::ID['CJHZ'] => 'CJHZ',
        IUserGroup::ID['LYKZ'] => 'LYKZ',
        IUserGroup::ID['GJCZ'] => 'GJCZ',
        IUserGroup::ID['DHX'] => 'DHX',
        IUserGroup::ID['MJPX'] => 'MJPX',
        IUserGroup::ID['GXX'] => 'GXX',
        IUserGroup::ID['JLSX'] => 'JLSX',
        IUserGroup::ID['ZJPX'] => 'ZJPX',
        IUserGroup::ID['GDSX'] => 'GDSX',
        IUserGroup::ID['SWJ'] => 'SWJ',
        IUserGroup::ID['RMFY'] => 'RMFY',
    );
}
